### ISSUE TITLE
MSI Not installing 

### ISSUE THREAD

**Issue by modz2014** [wjk/MSIExtractApp#145]
observations regarding your application available on the store. Upon installation, users have encountered issues with the functionality of the shell extension. Additionally, attempts to install the prebuilt MSIX package from your GitHub repository have been thwarted due to a trust certification error.

**Comment by modz2014** [comment]
@wjk i have fixed the issue for shell context menu but it doe not open the msi in the program also you should also add the extract the msi from the context menu when the users hovers over Open in MSI Viewer and show show menus like extract here\ or open in msi viewer would be a good idea

**Comment by wjk** [comment]
@modz2014 I am sorry, but this repository is unmaintained. I will archive it.
