### ISSUE TITLE
File Extraction Failure

### ISSUE THREAD

**Issue by ColdWinterWind** [wjk/MSIExtractApp#61]
Just downloaded your app.  Thanks for making it FREE! 
 
The 'issue' is that if the *.msi references a *.cab file, if the *.cab is not present in the same directory as the *.msi file, then the extraction will fail with no error message.

For a DOS Dinosaur like me it's an easy fix; just keep the *.msi & *.cab files in the same directory.  But file operations newbies will undoubtedly grow frustrated and uninstall a perfectly good app.

Thanks again for making it free.

Luck to you,
ColdWinterWind

**Comment by wjk** [comment]
@ColdWinterWind I have just submitted for certification version 1.3.0 of MSI Viewer, which contains a fix for this bug. It should be available for download in a few days. Thanks for bringing it to my attention! 🚀
