### ISSUE TITLE
Not an issue, but a question regarding UWP and CAB archive files.

### ISSUE THREAD

**Issue by Noemata** [wjk/MSIExtractApp#64]
I need to extract the contents of a CAB file from a UWP app.  Any ideas?  Interop to a DLL is possible, just that the DLL has to conform to a specific subset of Win32.

**Comment by wjk** [comment]
See here: [https://docs.microsoft.com/en-us/uwp/win32-and-com/win32-apis](https://docs.microsoft.com/en-us/uwp/win32-and-com/win32-apis#apis-from-cabinetdll) (pay attention to the functions that start with `FDI`). This documentation indicates that you can use a subset of the system `cabinet.dll` APIs to extract data from CAB files, even when in an AppContainer. You will need to create P/Invokes yourself, as this project’s libraries use the `FCI` APIs, which are not available in the AppContainer. I don’t think there is a built-in way to create or write to CAB files while in an AppContainer, as you would use the `FCI` APIs to do that, and they are not Windows Store-compliant. (There are Linux-based libraries that can read and write CAB files independently of Windows, but be sure to check the license; many are licensed under LGPL, which has terms that are almost impossible to comply with when building an app for an app store.) Hope this helps!

**Comment by Noemata** [comment]
Good idea.  I'll have a look.  Keep forgetting that chunks of Win32 are accessible from UWP.  Thanks for the reminder.

**Comment by Noemata** [comment]
Your idea worked.  The only issue I ran into was making sure I worked around Win32 file access restrictions in the UWP sandbox.  Thank you.
